<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MimeMapping" Version="4.0.0" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\FileManager.Core\FileManager.Core.csproj" />
		<InternalsVisibleTo Include="FileManager.Infrastructure.Tests" />
	</ItemGroup>

</Project>
